   server:
     port: 2333
     address: 0.0.0.0
   lavalink:
     server:
       password: "wonyaku"
       sources:
         youtube: true
         bandcamp: true
         soundcloud: true
         twitch: true
         vimeo: true
         http: true
         local: false
       bufferDurationMs: 400
       frameBufferDurationMs: 5000
       youtubePlaylistLoadLimit: 100
       youtubeSearchEnabled: true
       soundcloudSearchEnabled: true
       playerUpdateInterval: 5
       gc-warnings: true
       trackStuckThresholdMs: 10000
       useSeekGhosting: true
       resamplingQuality: HIGH
       
   metrics:
     prometheus:
       enabled: true
       endpoint: /metrics
       
   ratelimit:
     ipBlocks: []
     excludedIps: []
     strategy: "LoadBalance"
     searchTriggersFail: true
     retryLimit: 3

   plugins:
     - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.1"
       repository: "https://maven.lavalink.dev/releases"
     - dependency: "com.dunctebot:skybot-lavalink-plugin:1.4.0"
     - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
       repository: "https://maven.lavalink.dev/releases"
       
   lavasrc:
     providers:
       - "dzisrc"
       - "ytsearch"
       - "scsearch"
     spotify:
       clientId: "TAMBAHKAN_CLIENT_ID_SPOTIFY_ANDA"
       clientSecret: "TAMBAHKAN_CLIENT_SECRET_SPOTIFY_ANDA"
       countryCode: "ID"
     applemusic:
       countryCode: "ID"
       mediaAPIToken: "TAMBAHKAN_APPLE_MUSIC_TOKEN_ANDA"
       
   logging:
     file:
       path: ./logs/
     level:
       root: INFO
       lavalink: INFO
       
   sentry:
     dsn: ""
     environment: "production"
     
   server:
     gracefulShutdown: true
     gracefulShutdownTimeout: 60000
     
   # Pengaturan filter dan audio quality
   filters:
     # Equalizer presets
     equalizer:
       - name: "Pop"
         bands:
           - band: 0
             gain: -0.05
           - band: 1
             gain: 0.05
           - band: 2
             gain: 0.3
           - band: 3
             gain: 0.1
           - band: 4
             gain: 0.1
       - name: "Bass Boost"
         bands:
           - band: 0
             gain: 0.2
           - band: 1
             gain: 0.15
           - band: 2
             gain: 0.1
           - band: 3
             gain: 0.05
     # Aktifkan semua filter yang tersedia
     volume: true
     equalizer: true
     karaoke: true
     timescale: true
     tremolo: true
     vibrato: true
     distortion: true
     rotation: true
     channelMix: true
     lowPass: true
     
   # Konfigurasi koneksi
   httpConfig:
     connectTimeout: 10000
     readTimeout: 10000
     userAgent: "Lavalink/4.0 (Custom/1.0)"